UAR-411: API call to retrieve private MO data
companieshouse/overseas-entities-api pull request #217
Opened 2023-04-20 18:17 UTC by RobertBromfield

### JIRA link

### Change description

### Work checklist

- [ ] Tests added where applicable

### Merge instructions

We are committed to keeping commit history clean, consistent and linear. To achieve this, this commit should be structured as follows:

```
<type>[optional scope]: <description>
```

and contain the following structural elements:

- fix: a commit that patches a bug in your codebase (this correlates with PATCH in semantic versioning),
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in semantic versioning),
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of any type,
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`, and others,
- footers other than `BREAKING CHANGE: <description>` may be provided.

2023-04-21 22:42 UTC, bantao-ch commented on src/main/java/uk/gov/companieshouse/overseasentitiesapi/utils/PrivateDataRetrievalHelper.java
Lets rename this class to be called PrivateDataRetrievalService and move to service package.
Also rename and move the corresponding test class.

2023-04-25 09:09 UTC, bbell-companieshouse requested changes

2023-04-25 09:09 UTC, bbell-companieshouse commented on src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/FilingsService.java
> +                          PrivateDataRetrievalService managingOfficerDataRetrievalHelper) {
Rename this variable

2023-05-02 11:42 UTC, vgummadala commented on src/main/java/uk/gov/companieshouse/overseasentitiesapi/service/PrivateDataRetrievalService.java
Line 46:
Does the ServiceException constructor allow passing additional argument to pass your var message? 
      var message = "Error Retrieving Managing Officer data for " + companyNumber;

2023-05-02 11:45 UTC, vgummadala approved these changes

2023-05-03 09:51 UTC, bbell-companieshouse approved these changes

2023-05-03 11:01 UTC, vgummadala approved these changes

2023-05-04 08:32 UTC, vgummadala approved these changes

2023-05-04 11:42 UTC, merged