Feature/uar 591 update json attributes
companieshouse/overseas-entities-api pull request #282
Opened 2023-06-15 13:31 UTC by AndreKramer7654

### JIRA link

https://companieshouse.atlassian.net/browse/UAR-591

### Change description

Add attributes on JSON elements related to changes.

Fix
isOnSanctionsList to be Boolean so it can be optional

Fix
address mappings to use line2 and town.

Rename 
corporateSoleName to corporateName as it's always that in the XML.

### Work checklist

- [ ] Tests added where applicable

### Merge instructions

We are committed to keeping commit history clean, consistent and linear. To achieve this, this commit should be structured as follows:

```
<type>[optional scope]: <description>
```

and contain the following structural elements:

- fix: a commit that patches a bug in your codebase (this correlates with PATCH in semantic versioning),
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in semantic versioning),
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of any type,
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`, and others,
- footers other than `BREAKING CHANGE: <description>` may be provided.

2023-06-15 14:57 UTC, bantao-ch approved these changes

2023-06-15 15:00 UTC, azafarCH approved these changes
changes for dueDiligence look good 👍

2023-06-15 15:03 UTC, bantao-ch requested changes
Need a change to Presenter attribute -- name to "full_name"

2023-06-15 15:49 UTC, AndreKramer7654 commented
> Need a change to Presenter attribute -- name to "full_name"

Done but fullName as JSON is camel cased elesewhere

2023-06-16 07:15 UTC, bantao-ch commented on src/main/java/uk/gov/companieshouse/overseasentitiesapi/model/updatesubmission/Presenter.java
> +    @JsonProperty("fullName")
As discussed we will instead create a new Presenter class to match in CHIPS Filing Consumer

2023-06-16 07:16 UTC, bantao-ch approved these changes

2023-06-16 07:58 UTC, jkayyala approved these changes

2023-06-16 08:01 UTC, merged